### ISSUE TITLE
new feature: omit_attrs

### ISSUE THREAD

**Issue by nabbisen** [nabbisen/htmlproc-rs#6]
2 patterns available

- style: remove from all tags
- span.style: "." combined like JSONPath - remove from specific tag only

**Comment by getreu** [comment]
Can `omit_attrs` and `omit_enclosure` be combined in order to parse the HTML tree only once?

**Comment by nabbisen** [comment]
@getreu  
The project policy is in readme:

> Each function is offered as a single feature, so the dependencies are kept small.
